#!/usr/bin/python3
'''
Retrieve a password from the AW secrets manager and store it in a file.

Usage: get-password <id> <file> <owner>
'''

import sys
import os
import stat
import pwd
import json
import requests
import boto3


def main():
    ''' Do it
    '''
    secret_id = sys.argv[1]
    password_file = sys.argv[2]
    owner = sys.argv[3]

    availability_zone = requests.get(
        'http://169.254.169.254/latest/meta-data/placement/availability-zone').text

    region = availability_zone[:-1]

    client = boto3.client('secretsmanager', region_name=region)

    secret_value = client.get_secret_value(SecretId=secret_id)

    password = json.loads(secret_value['SecretString'])['password']

    open(password_file, 'w').write(password)

    os.chown(password_file, pwd.getpwnam(owner).pw_uid, -1)

    os.chmod(password_file, stat.S_IREAD)


if __name__ == "__main__":
    main()
