#!/usr/bin/python3
'''
Retrieve a password from the AW secrets manager and store it in a file.

Usage: get-password <id> <file>
'''

import sys
import json
import requests
import boto3


def main():
    ''' Do it
    '''
    # Get our AWS region from the instance metadata
    #
    availability_zone = requests.get(
        'http://169.254.169.254/latest/meta-data/placement/availability-zone').text

    region = availability_zone[:-1]

    client = boto3.client('secretsmanager', region_name=region)

    secret_value = json.loads(client.get_secret_value(SecretId=sys.argv[1]))

    password = secret_value['SecretString']['password']

    open(sys.argv[1], 'w').write(password)


if __name__ == "__main__":
    main()
