#!/bin/bash

export FLASK_APP=minitwit.py
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

if [ ! -f /var/minitwit/minitwit.db ] || [ -n "${INIT_DB}" ]; then
  echo "Initializing database at /var/minitwit/minitwit.db"
  ./init-db
fi

flask run --host=0.0.0.0 --with-threads --no-debugger --no-reload
